version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=base64:PQB+snriq+MAIEsHLEWnDAi5EvP5uHVs73mn+ozcBjs=
      - APP_DEBUG=false
      - APP_TIMEZONE=UTC
      - APP_URL=http://localhost:8000
      - FRONTEND_URL=http://localhost:3000
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      - APP_MAINTENANCE_STORE=database
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=srv504.hstgr.io
      - DB_PORT=3306
      - DB_DATABASE=u192611594_smartschool_DB
      - DB_USERNAME=u192611594_smartschool
      - DB_PASSWORD=j:?ETHpuTmjbk7#
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=pusher
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - CACHE_STORE=database
      - CACHE_PREFIX=
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - PUSHER_APP_ID=1974471
      - PUSHER_APP_KEY=306c6f59ed824a6e038a
      - PUSHER_APP_SECRET=21be618cbaef392be257
      - PUSHER_APP_CLUSTER=eu
      - PUSHER_HOST=
      - PUSHER_PORT=443
      - PUSHER_SCHEME=https
      - MAIL_MAILER=smtp
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=Smart School Suite
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - VITE_APP_NAME=Laravel
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    restart: unless-stopped

networks:
  default:
    driver: bridge
