name: Build and Push Docker Image

on:
  push:
    branches:
      - bill2
  pull_request:
    branches:
      - bill2

env:
  REGISTRY: docker.io
  IMAGE_NAME: school-smart-suite-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Create .env file for build
      run: |
        cat > .env << EOF
        APP_NAME=Laravel
        APP_ENV=production
        APP_KEY=base64:PQB+snriq+MAIEsHLEWnDAi5EvP5uHVs73mn+ozcBjs=
        APP_DEBUG=false
        APP_TIMEZONE=UTC
        APP_URL=http://localhost:8000
        FRONTEND_URL=http://localhost:3000
        APP_LOCALE=en
        APP_FALLBACK_LOCALE=en
        APP_FAKER_LOCALE=en_US
        APP_MAINTENANCE_DRIVER=file
        APP_MAINTENANCE_STORE=database
        BCRYPT_ROUNDS=12
        LOG_CHANNEL=stack
        LOG_STACK=single
        LOG_DEPRECATIONS_CHANNEL=null
        LOG_LEVEL=debug
        DB_CONNECTION=mysql
        DB_HOST=srv504.hstgr.io
        DB_PORT=3306
        DB_DATABASE=u192611594_smartschool_DB
        DB_USERNAME=u192611594_smartschool
        DB_PASSWORD=j:?ETHpuTmjbk7#
        SESSION_DRIVER=database
        SESSION_LIFETIME=120
        SESSION_ENCRYPT=false
        SESSION_PATH=/
        SESSION_DOMAIN=null
        BROADCAST_CONNECTION=pusher
        FILESYSTEM_DISK=local
        QUEUE_CONNECTION=database
        CACHE_STORE=database
        CACHE_PREFIX=
        MEMCACHED_HOST=127.0.0.1
        REDIS_CLIENT=phpredis
        REDIS_HOST=127.0.0.1
        REDIS_PASSWORD=null
        REDIS_PORT=6379
        PUSHER_APP_ID=1974471
        PUSHER_APP_KEY=306c6f59ed824a6e038a
        PUSHER_APP_SECRET=21be618cbaef392be257
        PUSHER_APP_CLUSTER=eu
        PUSHER_HOST=
        PUSHER_PORT=443
        PUSHER_SCHEME=https
        MAIL_MAILER=smtp
        MAIL_HOST=127.0.0.1
        MAIL_PORT=1025
        MAIL_USERNAME=null
        MAIL_PASSWORD=null
        MAIL_ENCRYPTION=null
        MAIL_FROM_ADDRESS=hello@example.com
        MAIL_FROM_NAME="Smart School Suite"
        AWS_ACCESS_KEY_ID=
        AWS_SECRET_ACCESS_KEY=
        AWS_DEFAULT_REGION=us-east-1
        AWS_BUCKET=
        AWS_USE_PATH_STYLE_ENDPOINT=false
        VITE_APP_NAME=Laravel
        EOF
        
    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}
